### ISSUE TITLE
Mass Rebuild Report 2024-12-07

### ISSUE THREAD

**Issue by tstellar** [fedora-llvm-team/llvm-snapshots#914]
- [ ] ~~[qt6-qtbase](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8356778/)~~
- [ ] ~~[qt6-qtcoap](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349693/)~~
- [ ] ~~[gstreamer1-plugins-good](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350254/)~~
- [ ] ~~[gstreamer1-plugins-bad-free](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349760/)~~
- [ ] ~~[python-awscrt](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349783/)~~
- [ ] ~~[qt6-qtgraphs](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350198/)~~
- [ ] ~~[qt6-qtwebchannel](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349321/)~~
- [ ] ~~[qt6-qtlocation](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350388/)~~
- [ ] ~~[qt6-qtserialport](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349891/)~~
- [ ] ~~[qt6-qtnetworkauth](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349821/)~~
- [x] [conntrack-tools](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350359/): Upstream Bug.
- [x] #950
- [ ] ~~[qt6-qtconnectivity](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350026/)~~
- [ ] ~~[qt6-qtremoteobjects](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350461/)~~
- [ ] [mod_proxy_cluster](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349432/)
- [ ] ~~[qt6-qtpositioning](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350253/)~~
- [ ] ~~[qt6-qtcharts](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349578/)~~
- [ ] ~~[qt6-qtlottie](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349511/)~~
- [ ] ~~[qt6-qt5compat](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349366/)~~
- [ ] ~~[qt6-qtsensors](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349506/)~~
- [ ] ~~[qt6-qtlanguageserver](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349973/)~~
- [ ] ~~[gstreamer1-plugins-ugly-free](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349521/)~~
- [ ] ~~[qt6-qtmultimedia](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349981/)~~
- [ ] ~~[gstreamer1-plugins-base](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349910/)~~
- [ ] ~~[qt6-qtwebview](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349453/)~~
- [ ] ~~[qt6-qtimageformats](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349564/)~~
- [ ] ~~[qt6-qtquick3dphysics](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349930/)~~
- [ ] ~~[qt6-qtshadertools](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349745/)~~
- [ ] ~~[qt6-qtquicktimeline](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349770/)~~
- [ ] ~~[qt6-qtsvg](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349422/)~~
- [ ] ~~[qt6-qt3d](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349983/)~~
- [ ] ~~[gstreamer1-rtsp-server](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349589/)~~
- [ ] ~~[qt6-qthttpserver](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350051/)~~
- [ ] ~~[qt6-qtwebsockets](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350319/)~~
- [ ] ~~[qt6-qtwayland](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350353/)~~
- [ ] ~~[qt6-qtvirtualkeyboard](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349813/)~~
- [ ] ~~[qt6-qtmqtt](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349619/)~~
- [x] [adcli](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349232/) Type aliasing bug upstream.
- [ ] ~~[qt6-qtopcua](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349684/)~~
- [ ] ~~[gstreamer1-plugin-libav](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349723/)~~
- [ ] ~~[qt6-qtscxml](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349719/)~~
- [ ] ~~[qt6-qtdeclarative](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350158/)~~
- [ ] [python-gevent](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349308/)
- [ ] ~~[qt6-qtspeech](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349694/)~~
- [ ] ~~[qt6-qtserialbus](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349715/)~~
- [ ] ~~[qt6-qtdatavis3d](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8350366/)~~

**Comment by tstellar** [comment]
The qt failures are because qt6-qtbase is failing to build (not related to clang) so anything that depends on it also fails.

**Comment by tstellar** [comment]
The gstreamer failures are also due to a dependency issue.

**Comment by tstellar** [comment]
The adcli failure is a real regression.  I've bisected it to https://github.com/llvm/llvm-project/commit/7954a0514ba7de40dba6c598af830fd1b7a8bf0c

**Comment by tstellar** [comment]
Upstream bug for adcli: https://github.com/llvm/llvm-project/issues/119099

**Comment by tstellar** [comment]
[python-awscrt](https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/fedora-41-clang-20/build/8349783/) seems like an unrelated failure:

```
+ /usr/bin/python3 -Bs /usr/lib/rpm/redhat/pyproject_buildrequires.py --generate-extras --python3_pkgversion 3 --wheeldir /builddir/build/BUILD/python-awscrt-0.22.4-build/awscrt-0.22.4/pyproject-wheeldir --output /builddir/build/BUILD/python-awscrt-0.22.4-build/python-awscrt-0.22.4-1.fc41.x86_64-pyproject-buildrequires
Handling setuptools >= 40.8 from default build backend
Requirement satisfied: setuptools >= 40.8
   (installed: setuptools 69.2.0)
Traceback (most recent call last):
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 721, in main
    generate_requires(
    ~~~~~~~~~~~~~~~~~^
        include_runtime=args.runtime,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
        config_settings=parse_config_settings_args(args.config_settings),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 603, in generate_requires
    generate_build_requirements(backend, requirements)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 293, in generate_build_requirements
    new_reqs = get_requires(config_settings=requirements.config_settings)
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
    ~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
    ~~~~^^^^^^^^^^^^^^^^
  File "<string>", line 15, in <module>
ModuleNotFoundError: No module named 'wheel'
```

**Comment by tstellar** [comment]
It looks like the pybind11 failure was also caused by https://github.com/llvm/llvm-project/commit/7954a0514ba7de40dba6c598af830fd1b7a8bf0c.

**Comment by tstellar** [comment]
Upstream bug for pybind11: https://github.com/llvm/llvm-project/issues/119507

**Comment by tstellar** [comment]
We are done reviewing this results.
